### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by PiotrGlab** [monitool/monitool-sensors#1]
One of the statements given by a supervisor is a review in technologies connected with sensors. In this point we should make a recognition of solutions which are used commonly in projects such like ours.
What is demanded:

```
library which monitors sensors
library which displays charts; for example : an average percentage of CPU usage in one hour, minute by minute, etc.
```

Responsible for that points are @slawkow68 and @ppalus.

All your thinkings, tools which you will find, brief description of their prose and cons attach to Wiki. That will give a perspective of your part of system to the rest of the team.

**Comment by ppalus** [comment]
For sensors I suggest use Java, there is easy to use interface for monitoring system resources:
http://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html

Should sensor implement API, for example: for remote shut down sensor or getting selective data (CPU load only)?

**Comment by slawkow68** [comment]
I'm afraid, but this bult-in monitoring features are not working properly on Windows, returned value for CPU load is -1, what means it's this function is unavailable. I've also checked https://support.hyperic.com/display/SIGAR/Home but the same problem ocurred.

Sensors have not rest or other type of public interface, so the only elegant way is to ask server if sensor should change type of sending information or shutdown itself. But  I don't really know if this feature is required.

**Comment by slawkow68** [comment]
I've found library, which can successfully measure cpu load on Windows 8. This library can be used not only for measuring cpu load, but also for memory stats, however the last one can be also achived with proposed built-in Java tool. This library has quite low level api, so it will be nice to find something better, but this is already checked, working solution.

https://github.com/jezhumble/javasysmon
http://mvnrepository.com/artifact/com.outr.javasysmon/javasysmon_2.10/0.3.4

**Comment by ppalus** [comment]
System CPU usage and memory usage we're getting via Java class com.sun.management.OperatingSystemMXBean. Data is converted to JSON format and sent using OkHttp library.
