### ISSUE TITLE
Sensors returing -1

### ISSUE THREAD

**Issue by ppalus** [monitool/monitool-sensors#2]
Hi,
I've heard that in some particular situations sensors return -1 as one of measurement data. Can anyone describe issue with more details? I can't replicate bug, I've ran sensor for over 30min and not even once got -1.

**Comment by akaluzinski** [comment]
@ppalus Sometimes sensor returns CPU load as -1 instead of expected positive value. I've noticed that it happens only on Windows and frequency of bug is totally undetermined.
