### ISSUE TITLE
Registred sensor: null

### ISSUE THREAD

**Issue by maniolek** [monitool/monitool-sensors#3]
I installed sensor on my pc, and after quick install-bug-solving I was lucky to start it. After short while I've noticed that my registred sensor is null. How can I assign value there? Shouldn't this be described in docs? 

Would be nice to create step by step instruction how to get repo, install maven and other dependecies like java. If you are installing sensor on fresh unix/win distribution that would be nice to know.

**Comment by maniolek** [comment]
Oh, ofc I know that sensor must be registred on api side, but how it should be connected to my pc?

https://github.com/monitool/docs/wiki/Sensors-build-and-run doesn't say to much...

**Comment by DamianChodorek** [comment]
Guys from sensors should update their application to be compatibile with new wersion of API ;)
Last time I checked it was enough to run sensor program on my computer.

**Comment by maniolek** [comment]
Okay, great. @slawkow68 can you update app as asap as possible? Since API db has been cleaned I cannot do anything, to be honest. I need at least couple measurement sets.

**Comment by PiotrGlab** [comment]
I had spoken with @slawkow68 and he told me that sensor app is updated
today.

2015-04-27 22:50 GMT+02:00 maniolek notifications@github.com:

**Comment by slawkow68** [comment]
I'm afraid that sensors update have to wait for tomorrow due to problem with merging simple socket-based solution of single instance application with already used cron scheduler.

**Comment by slawkow68** [comment]
URLs for new server's API have been updated - please check if it works. The problem with only one instance still exists, but it shouldn't block you in any way.

**Comment by slawkow68** [comment]
One instance sensor is now working, the solution is not the pretiest one, but working - sensor is trying to bind to some particular socket, if it fails it assumes that another sensor is already bound to this socket, so another sensor instance is already working.

**Comment by maniolek** [comment]
'mvn3 clean install' command give me that output. 
Have you met with this error?

```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sensors 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sensors ---
[INFO] Deleting /home/matt/monitool-sensors/sensors/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sensors ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/matt/monitool-sensors/sensors/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ sensors ---
[INFO] Compiling 11 source files to /home/matt/monitool-sensors/sensors/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/matt/monitool-sensors/sensors/src/main/java/io/github/monitool/sensors/App.java:[36,25] error: multi-catch statement is not supported in -source 1.5
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.265 s
[INFO] Finished at: 2015-04-30T07:26:12+01:00
[INFO] Final Memory: 11M/213M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project sensors: Compilation failure
[ERROR] /home/matt/monitool-sensors/sensors/src/main/java/io/github/monitool/sensors/App.java:[36,25] error: multi-catch statement is not supported in -source 1.5
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

mvn3 -v

```
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Maven home: /usr/share/maven3
Java version: 1.7.0_55, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.11.0-12-generic", arch: "amd64", family: "unix"
```

**Comment by slawkow68** [comment]
Fixed. I had to set correct java version in POM file. I hadn't met this error because I used to compile this program only through eclipse.
